export const TITLES = [
  // 액션 (18)
  { id: 1, title: "Extraction 2", genre: "action", image: "https://image.tmdb.org/t/p/w200/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg" },
  { id: 2, title: "John Wick: Chapter 4", genre: "action", image: "https://image.tmdb.org/t/p/w200/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg" },
  { id: 3, title: "The Gray Man", genre: "action", image: "https://image.tmdb.org/t/p/w200/8cXbitsS6dWQ5gfMTZdorpAAzEH.jpg" },
  { id: 4, title: "6 Underground", genre: "action", image: "https://image.tmdb.org/t/p/w200/lnWkyG3LLgbbrIEeyl5mK5VRFe4.jpg" },
  { id: 5, title: "Red Notice", genre: "action", image: "https://image.tmdb.org/t/p/w200/lAXONuqg41NwUMuzMiFvicDET9Y.jpg" },
  { id: 6, title: "The Equalizer 3", genre: "action", image: "https://image.tmdb.org/t/p/w200/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg" },
  { id: 7, title: "Fast X", genre: "action", image: "https://image.tmdb.org/t/p/w200/fiVW06jE7z9YnO4trhaMEdclSiC.jpg" },
  { id: 8, title: "Top Gun: Maverick", genre: "action", image: "https://image.tmdb.org/t/p/w200/62HCnUTziyWcpDaBO2i1DX17ljH.jpg" },
  { id: 9, title: "Mission: Impossible - Dead Reckoning", genre: "action", image: "https://image.tmdb.org/t/p/w200/NNxYkU70HPurnNCSiCjYAmacwm.jpg" },
  { id: 10, title: "Black Adam", genre: "action", image: "https://image.tmdb.org/t/p/w200/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg" },
  { id: 11, title: "The Batman", genre: "action", image: "https://image.tmdb.org/t/p/w200/74xTEgt7R36Fpooo50r9T25onhq.jpg" },
  { id: 12, title: "The Matrix Resurrections", genre: "action", image: "https://image.tmdb.org/t/p/w200/8c4a8kE7PizaGQQnditMmI1xbRp.jpg" },
  { id: 13, title: "Tenet", genre: "action", image: "https://image.tmdb.org/t/p/w200/k68nPLbIST6NP96JmTxmZijEvCA.jpg" },
  { id: 14, title: "No Time To Die", genre: "action", image: "https://image.tmdb.org/t/p/w200/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg" },
  { id: 15, title: "Dune", genre: "action", image: "https://image.tmdb.org/t/p/w200/d5NXSklXo0qyIYkgV94XAgMIckC.jpg" },
  { id: 16, title: "Wakanda Forever", genre: "action", image: "https://image.tmdb.org/t/p/w200/sv1xJUazXeYqALzczSZ3O6nkH75.jpg" },
  { id: 17, title: "The Flash", genre: "action", image: "https://image.tmdb.org/t/p/w200/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg" },
  { id: 18, title: "Shang-Chi", genre: "action", image: "https://image.tmdb.org/t/p/w200/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg" },

  // 애니메이션 (35)
  { id: 19, title: "Your Name", genre: "animation", image: "https://image.tmdb.org/t/p/w200/q719jXXEzOoYaps6babgKnONONX.jpg" },
  { id: 20, title: "Spirited Away", genre: "animation", image: "https://image.tmdb.org/t/p/w200/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg" },
  { id: 21, title: "My Neighbor Totoro", genre: "animation", image: "https://image.tmdb.org/t/p/w200/rtGDOeG9LzoerkDGZF9dnVeLppL.jpg" },
  { id: 22, title: "Princess Mononoke", genre: "animation", image: "https://image.tmdb.org/t/p/w200/jHWkBXX0JYk9RZx8P6haFFQ1W8M.jpg" },
  { id: 23, title: "Howl's Moving Castle", genre: "animation", image: "https://image.tmdb.org/t/p/w200/TkTPELv4kC3u1lkloush8skOjE.jpg" },
  { id: 24, title: "Demon Slayer: Mugen Train", genre: "animation", image: "https://image.tmdb.org/t/p/w200/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg" },
  { id: 25, title: "Attack on Titan", genre: "animation", image: "https://image.tmdb.org/t/p/w200/sHim8xqW8mFEO1cBVN3dA3tEFAh.jpg" },
  { id: 26, title: "Naruto", genre: "animation", image: "https://image.tmdb.org/t/p/w200/vauCEnR7CiyBDzRCeElKkCaXIYu.jpg" },
  { id: 27, title: "One Piece", genre: "animation", image: "https://image.tmdb.org/t/p/w200/il8T1ZtM2ndyJY3GfK3l3K9KzZf.jpg" },
  { id: 28, title: "Jujutsu Kaisen", genre: "animation", image: "https://image.tmdb.org/t/p/w200/hFWP5HkbVEe40hrXgtCeQxoccHE.jpg" },
  { id: 29, title: "Chainsaw Man", genre: "animation", image: "https://image.tmdb.org/t/p/w200/npdB6eFzizki0WaZ1OvKcJrWe97.jpg" },
  { id: 30, title: "Suzume", genre: "animation", image: "https://image.tmdb.org/t/p/w200/vIeu8WysZrTSFb2uhPViKjX9EcC.jpg" },
  { id: 31, title: "The Boy and the Heron", genre: "animation", image: "https://image.tmdb.org/t/p/w200/jDQPkgzerGophKRRn7MKm071vCU.jpg" },
  { id: 32, title: "A Silent Voice", genre: "animation", image: "https://image.tmdb.org/t/p/w200/tuFaWiqX0TXoWu7DGNcmX3UW7.jpg" },
  { id: 33, title: "Kiki's Delivery Service", genre: "animation", image: "https://image.tmdb.org/t/p/w200/3IP3rUWL3M6YzwD8G1GfKjM8pFf.jpg" },
  { id: 34, title: "The Wind Rises", genre: "animation", image: "https://image.tmdb.org/t/p/w200/jfwSexzlIzaOgxP9A8bTA6t8YYb.jpg" },
  { id: 35, title: "One Punch Man", genre: "animation", image: "https://image.tmdb.org/t/p/w200/iE3s0lG5QVdEHOEZnoAxjmMtvne.jpg" },
  { id: 36, title: "Mob Psycho 100", genre: "animation", image: "https://image.tmdb.org/t/p/w200/qjk4g6qfTzjHVn3bh9sR2rY2sLG.jpg" },
  { id: 37, title: "Dr. Stone", genre: "animation", image: "https://image.tmdb.org/t/p/w200/4Iu5fOaewpCdBkxVFEleZSVS4vt.jpg" },
  { id: 38, title: "Blue Giant", genre: "animation", image: "https://image.tmdb.org/t/p/w200/fvQMy1zMQAFJ3PSLdnz8WAaVjzs.jpg" },
  { id: 39, title: "Ponyo", genre: "animation", image: "https://image.tmdb.org/t/p/w200/yp8vEZflGynlEylxEesbYasc06i.jpg" },
  { id: 40, title: "Wolf Children", genre: "animation", image: "https://image.tmdb.org/t/p/w200/iQpA6YkM3ZrCzRcd9Eihd3J5vdR.jpg" },
  { id: 41, title: "Summer Wars", genre: "animation", image: "https://image.tmdb.org/t/p/w200/8LTaQOfIN6qZg8Zk6oNQb6YQ6Vu.jpg" },
  { id: 42, title: "Belle", genre: "animation", image: "https://image.tmdb.org/t/p/w200/wANARQGud9sjTiz4W4fVx2Dfz1K.jpg" },
  { id: 43, title: "Weathering With You", genre: "animation", image: "https://image.tmdb.org/t/p/w200/qgrkVrFU0fWxQ9rz4GckyTQjx39.jpg" },
  { id: 44, title: "Whisper of the Heart", genre: "animation", image: "https://image.tmdb.org/t/p/w200/lEkznmQmCQsmCQc9vKjZr8N9bTw.jpg" },
  { id: 45, title: "Erased", genre: "animation", image: "https://image.tmdb.org/t/p/w200/1j8p7YAP0KnkXkkkbK8Hk2v7Y2d.jpg" },
  { id: 46, title: "Made in Abyss", genre: "animation", image: "https://image.tmdb.org/t/p/w200/kR7WFeD31DzLO9RwkgPfA2wZGPx.jpg" },
  { id: 47, title: "Vivy: Fluorite Eye's Song", genre: "animation", image: "https://image.tmdb.org/t/p/w200/tz6T8xV6t84ZrKxR9zfoC1yUdM6.jpg" },
  { id: 48, title: "Tokyo Ghoul", genre: "animation", image: "https://image.tmdb.org/t/p/w200/bPvfmwEWxWwfvYV4hBtJZbVlfzC.jpg" },
  { id: 49, title: "Death Note", genre: "animation", image: "https://image.tmdb.org/t/p/w200/gQvBvFh4lfGGWvZtH5p3T0xk2Jz.jpg" },
  { id: 50, title: "Fullmetal Alchemist: Brotherhood", genre: "animation", image: "https://image.tmdb.org/t/p/w200/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg" },
  { id: 51, title: "Neon Genesis Evangelion", genre: "animation", image: "https://image.tmdb.org/t/p/w200/y6DTPtTHiRjYjQnq5CulBLWR6Tc.jpg" },
  { id: 52, title: "Cowboy Bebop", genre: "animation", image: "https://image.tmdb.org/t/p/w200/7IXLzq0VFh2T0F5pHqACgiXSWsL.jpg" },
  { id: 53, title: "Spirited Away (Re-release)", genre: "animation", image: "https://image.tmdb.org/t/p/w200/oRvMaJOmapypFUcQqpgHMZA6qL9.jpg" },

  // 스릴러 (25)
  { id: 54, title: "Mindhunter", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/fkjrj4lJjfY1J3ZlVvG7P52bjhQ.jpg" },
  { id: 55, title: "Gone Girl", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/qymaJhucquUwjpb8oiqynMeXnID.jpg" },
  { id: 56, title: "Bird Box", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/rGfGfgL2pEPCfhIvqHXieXFn7gp.jpg" },
  { id: 57, title: "You", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/8mJbs5Tj8CFlS6H6Y5VxjGJYIgQ.jpg" },
  { id: 58, title: "Fight Club", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg" },
  { id: 59, title: "Se7en", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/6yoghtyTpznpBik8EngEmJskVUO.jpg" },
  { id: 60, title: "Inception", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg" },
  { id: 61, title: "Shutter Island", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/kve20tXwUZpu4GUX8l6X7Z4jmL6.jpg" },
  { id: 62, title: "Nightcrawler", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/8R6lP6YBoe3fJddJzFz7S2Z0YQY.jpg" },
  { id: 63, title: "The Girl with the Dragon Tattoo", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/zq5kZ2Wb8KQNt8rMC1wT3xkP2uZ.jpg" },
  { id: 64, title: "Zodiac", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/6YmeO4pB7XTh8P8F960O1uA14JO.jpg" },
  { id: 65, title: "The Prestige", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg" },
  { id: 66, title: "Prisoners", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/tuZhZ6biFMr5n9YSVuHOJnNL1uU.jpg" },
  { id: 67, title: "The Departed", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/7XM0y6C7fH6G96mfWZfFxo5hq8z.jpg" },
  { id: 68, title: "The Invisible Guest", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/zAYRe2bJxpWTVrwwmBc00VFkAf4.jpg" },
  { id: 69, title: "The Invitation", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/pL3VJ7DshVfJUzG7fV4BZhECmoX.jpg" },
  { id: 70, title: "Run", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/5HKRQfZ8jG8g2kMecm4XQ3AAMFa.jpg" },
  { id: 71, title: "Get Out", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg" },
  { id: 72, title: "Us", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/xvYCZ740XvngXK0FNeSNVTJJJ5v.jpg" },
  { id: 73, title: "Parasite", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg" },
  { id: 74, title: "Split", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/bqb9WsmZmDIKxqYmBJ9lj7J6hzn.jpg" },
  { id: 75, title: "Glass", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/svIDTNUoajS8dLEo7EosxvyAsgJ.jpg" },
  { id: 76, title: "Joker", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg" },
  { id: 77, title: "Oldboy", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg" },
  { id: 78, title: "The Handmaiden", genre: "thriller", image: "https://image.tmdb.org/t/p/w200/wVU2p9JdYvZrgkxJkR9y2gYiq4P.jpg" },
];